### ISSUE TITLE
mistake in readme + conda julia discussion

### ISSUE THREAD

**Issue by ngam** [QuantStack/xtensor-julia#41]
Hi,
 I was wondering if we could talk about packaging for julia inside the conda-forge framework.
 @mkitti and I from the julia-feedstock are trying to figure out what people really want and how we can help.
 We recently did some housekeeping and fixes and we would like your input.

---

In your readme here: https://github.com/xtensor-stack/xtensor-julia#installation-of-the-julia-package, there are some typos. It should be `conda install xtensor-julia -c conda-forge`

**Comment by SylvainCorlay** [comment]
> I was wondering if we could talk about packaging for julia inside the conda-forge framework.
@mkitti and I from the julia-feedstock are trying to figure out what people really want and how we can help.
We recently did some housekeeping and fixes and we would like your input.

Hey, thank you for your message. I would love to chat about this. I stand more on the conda/mamba side of the stack but I would be very happy to help with this effort.

*****
> In your readme here: https://github.com/xtensor-stack/xtensor-julia#installation-of-the-julia-package, there are some typos. It should be conda install xtensor-julia -c conda-forge

Thanks, I fixed the typo!

**Comment by mkitti** [comment]
xref: https://github.com/JuliaInterop/CxxWrap.jl/issues/309#issuecomment-1003910771
